### ISSUE TITLE
turn on write hook point 

### ISSUE THREAD

**Issue by tfxidian** [bytedance/Elkeid#347]
I can't find   informations generated by write syacall in the Elkeid output data,  thus i search the document and find this [Hook list](https://github.com/bytedance/Elkeid/tree/main/driver#:~:text=pod%20name-,Hook%20List,-Hook).  It seems that write syscall is off by default. 
 **could you please tell me how to turn on write hook point?**

**Comment by EBWi11** [comment]
default the write hook is close, because it will generate a lot of data, we only turn on it whe the 'sandbox' model. so you need set :https://github.com/bytedance/Elkeid/blob/main/driver/LKM/src/smith_hook.c#L42 to 1, or open the sandbox model: https://github.com/bytedance/Elkeid/blob/main/driver/LKM/src/smith_hook.c#L19, sandbox model can collect more behaivor like the open,kill.., you can get list from: https://github.com/bytedance/Elkeid/blob/main/driver/LKM/src/smith_hook.c#L4373

and when you edit the driver code, you must rebuild kernel module and redeploy it.
